// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package japanesedelivery.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import japanesedelivery.proxies.ZtoImportBcOrder;
import japanesedelivery.proxies.ZtoIntlOrderItem;
import japanesedelivery.proxies.ZtoOrderEntity;

public class AddImportOrder extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __ztoImportBcOrder;
	private japanesedelivery.proxies.ZtoImportBcOrder ztoImportBcOrder;
	private java.util.List<IMendixObject> __ztoIntlOrderItemList;
	private java.util.List<japanesedelivery.proxies.ZtoIntlOrderItem> ztoIntlOrderItemList;
	private IMendixObject __ztoOrderEntity;
	private japanesedelivery.proxies.ZtoOrderEntity ztoOrderEntity;
	private IMendixObject __channelConfig;
	private japanesedelivery.proxies.ChannelConfig channelConfig;

	public AddImportOrder(IContext context, IMendixObject ztoImportBcOrder, java.util.List<IMendixObject> ztoIntlOrderItemList, IMendixObject ztoOrderEntity, IMendixObject channelConfig)
	{
		super(context);
		this.__ztoImportBcOrder = ztoImportBcOrder;
		this.__ztoIntlOrderItemList = ztoIntlOrderItemList;
		this.__ztoOrderEntity = ztoOrderEntity;
		this.__channelConfig = channelConfig;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.ztoImportBcOrder = this.__ztoImportBcOrder == null ? null : japanesedelivery.proxies.ZtoImportBcOrder.initialize(getContext(), __ztoImportBcOrder);

		this.ztoIntlOrderItemList = java.util.Optional.ofNullable(this.__ztoIntlOrderItemList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__ztoIntlOrderItemListElement -> japanesedelivery.proxies.ZtoIntlOrderItem.initialize(getContext(), __ztoIntlOrderItemListElement))
			.collect(java.util.stream.Collectors.toList());

		this.ztoOrderEntity = this.__ztoOrderEntity == null ? null : japanesedelivery.proxies.ZtoOrderEntity.initialize(getContext(), __ztoOrderEntity);

		this.channelConfig = this.__channelConfig == null ? null : japanesedelivery.proxies.ChannelConfig.initialize(getContext(), __channelConfig);

		// BEGIN USER CODE
        String name = channelConfig.getname();
        if(name.equals("ZTO")){
            // 调用ZtoAddBcImportOrder.java
            ZtoAddBcImportOrder ztoAddBcImportOrder = new ZtoAddBcImportOrder(getContext(), __ztoImportBcOrder, __ztoIntlOrderItemList, __ztoOrderEntity, __channelConfig);
            return ztoAddBcImportOrder.executeAction(); // 直接返回ZTO的处理结果
        }else if (name.equals("QunHui")){
            // 调用QunhuiAddImportOrder.java
            QunhuiAddImportOrder qunhuiAddImportOrder = new QunhuiAddImportOrder(getContext(), __ztoImportBcOrder, __ztoIntlOrderItemList, __ztoOrderEntity, __channelConfig);
            return qunhuiAddImportOrder.executeAction(); // 直接返回群辉的处理结果
        }
        
        // 如果渠道名称不匹配，抛出异常
        throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Unsupported channel: " + name);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "AddImportOrder";
	}

	// BEGIN EXTRA CODE

	// END EXTRA CODE
}
