// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package japanesedelivery.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import org.apache.commons.codec.digest.DigestUtils;

public class TokenCheck extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String timestamp;
	private java.lang.String companyName;
	private java.lang.String sign;

	public TokenCheck(IContext context, java.lang.String timestamp, java.lang.String companyName, java.lang.String sign)
	{
		super(context);
		this.timestamp = timestamp;
		this.companyName = companyName;
		this.sign = sign;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE

		// determine token for Japanese company

		String token = "Japanese_B202302122212_aux6";
		String shaHex = DigestUtils.shaHex(companyName + timestamp + token);
		if(shaHex.equals(sign)){
			return true;
		}
		return false;
		// throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TokenCheck";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
