// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package japanesedelivery.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class ZtoAddBcImportOrder extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __ztoImportBcOrder;
	private japanesedelivery.proxies.ZtoImportBcOrder ztoImportBcOrder;
	private java.util.List<IMendixObject> __intlOrderItemList;
	private java.util.List<japanesedelivery.proxies.IntlOrderItem> intlOrderItemList;
	private IMendixObject __orderEntity;
	private japanesedelivery.proxies.OrderEntity orderEntity;

	public ZtoAddBcImportOrder(IContext context, IMendixObject ztoImportBcOrder, java.util.List<IMendixObject> intlOrderItemList, IMendixObject orderEntity)
	{
		super(context);
		this.__ztoImportBcOrder = ztoImportBcOrder;
		this.__intlOrderItemList = intlOrderItemList;
		this.__orderEntity = orderEntity;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		this.ztoImportBcOrder = this.__ztoImportBcOrder == null ? null : japanesedelivery.proxies.ZtoImportBcOrder.initialize(getContext(), __ztoImportBcOrder);

		this.intlOrderItemList = java.util.Optional.ofNullable(this.__intlOrderItemList)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(__intlOrderItemListElement -> japanesedelivery.proxies.IntlOrderItem.initialize(getContext(), __intlOrderItemListElement))
			.collect(java.util.stream.Collectors.toList());

		this.orderEntity = this.__orderEntity == null ? null : japanesedelivery.proxies.OrderEntity.initialize(getContext(), __orderEntity);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ZtoAddBcImportOrder";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
