// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package japanesedelivery.actions;

import cn.hutool.json.JSONUtil;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Date;

public class ZtoSaveTracks extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String deliveryTrackNo;
	private java.lang.String tracksMessage;
	private java.util.Date tracksTime;
	private java.lang.String action;

	public ZtoSaveTracks(IContext context, java.lang.String deliveryTrackNo, java.lang.String tracksMessage, java.util.Date tracksTime, java.lang.String action)
	{
		super(context);
		this.deliveryTrackNo = deliveryTrackNo;
		this.tracksMessage = tracksMessage;
		this.tracksTime = tracksTime;
		this.action = action;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ZtoSaveTracks";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
