// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package advanced_excel.actions;

import advanced_excel.proxies.Data;
import advanced_excel.proxies.CellType;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.core.objectmanagement.member.*;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IMendixObjectMember;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * Create a list of Data from an object
 */
public class DataList_Create extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject ObjectInput;
	private java.lang.Long Row;
	private java.lang.String Columns;
	private java.lang.String Attributes;

	public DataList_Create(IContext context, IMendixObject ObjectInput, java.lang.Long Row, java.lang.String Columns, java.lang.String Attributes)
	{
		super(context);
		this.ObjectInput = ObjectInput;
		this.Row = Row;
		this.Columns = Columns;
		this.Attributes = Attributes;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		try
		{
			String cellType;
			IMendixObject data;
			IContext context = this.getContext();

			List<IMendixObject> DataList = new ArrayList<IMendixObject>();
			
			String[] attributes = Attributes == null ? new String[0] : Attributes.split(";");
			String[] columns = Columns == null ? new String[0] : Columns.split(";");
			
			for (int i = 0; i < attributes.length; i++) {
				IMendixObject obj = ObjectInput;
				
				List<IMendixObject> curObjs = Arrays.asList(ObjectInput);
				String attr = attributes[i];
				
				if (attr.contains("/")) {
					String[] paths = attr.split("/");
					int attPos = paths.length - 1;
					for (int j = 0; j < attPos; j++) {
						List<IMendixObject> objs = Core.retrieveByPath(context, curObjs.get(0), paths[j]);
						if (objs.size() > 1 && j < attPos - 1) { throw new Exception("too much associated object found: " + paths[i] + "\nPath: " + attr); }
						else if (objs.size() == 0) { curObjs = null; continue; }
						
						curObjs = objs;
					}
					attr = paths[attPos];
				}
				if (curObjs == null) { continue; }
				
				IMendixObjectMember<?> m = curObjs.get(0).getMember(context, attr);
				if (m.isVirtual()) {
					continue;
				}
				if (m instanceof MendixAutoNumber) {
					continue;
				}
				
				String valStr = "";
				var val = m.getValue(context);
				if (curObjs.size() > 1) {
					for (int j = 0; j < curObjs.size(); j++) {
						val = curObjs.get(j).getMember(context, attr).getValue(context);
						valStr = (j == 0 ? "" : valStr + ";") + (val == null ? "" : val.toString());
					}
				} else {
					valStr = val == null ? "" : val.toString();
				}
				
				cellType = "text";
				if (curObjs.size() > 1) { cellType = "text"; }
				else if (m instanceof MendixInteger) { cellType = "integer"; }
				else if (m instanceof MendixBoolean) { cellType = "boolean"; }
				else if (m instanceof MendixDecimal) { cellType = "decimal"; }
				else if (m instanceof MendixLong) { cellType = "integer"; }
				else if (m instanceof MendixDateTime) {
					cellType = "datetime";
					DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");  
					valStr = val == null ? "" : dateFormat.format((Date)val);
				}
				else { cellType = "text"; }
				
				data = Core.instantiate(context, "Advanced_Excel.Data");
				data.setValue​(context, "Row", Row.intValue());
				data.setValue​(context, "Column", Integer.parseInt(columns[i]));
				data.setValue​(context, "CellValue", valStr);
				data.setValue​(context, "CellType", cellType);
				DataList.add(data);
			}
			
			return DataList;
		} catch (Exception e) {
			logger.error("ERROR in Advanced_Excel.DataList_Create: " + e.getMessage() + "\n" + e.toString(), e);
			return null;
		} 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DataList_Create";
	}

	// BEGIN EXTRA CODE
	protected static ILogNode logger = Core.getLogger("Advanced_Excel");
	// END EXTRA CODE
}
